version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/dispatcher/code-deploy/
    overwrite: true
permissions:
  - object: /home/ubuntu/dispatcher/code-deploy/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
     - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/build_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root